{
    "name": "aggressive_market_making",   # Name of the strategy
    "type": "market_making",              # Type of strategy: market_making, arbitrage, etc
    "exchange": "muesliswap",             # Exchange to run the strategy on
    "n_orders": 2,                        # Number of orders to place on each side of the order book
    "delta": 0.02,                        # Base distance between orders as a fraction of the mid price (tighter than standard)
    "order_refresh_threshold": 0.15,      # Percentage change in price to trigger order refresh
    "loop_interval": 3,                   # Time in seconds between each loop (faster than standard)
    
    # Aggressive strategy specific parameters
    "volatility_multiplier": 1.5,         # How much volatility affects spread adjustment
    "min_delta": 0.005,                   # Minimum spread (0.5%)
    "max_delta": 0.05,                    # Maximum spread (5%)
    "price_history_length": 20,           # Number of price points to keep for volatility calculation
    
    "tokens": {                           # Tokens to trade
        "tMILK": {
            "hexname": "744d494c4b",
            "policy_id": "bd976e131cfc3956b806967b06530e48c20ed5498b46a5eb836b61c2",
            "amount": 1,
            "decimals": 0
        }
    } 
}
