{
    "name": "standard_market_making",   # Name of the strategy
    "type": "market_making",            # Type of strategy: market_making, arbitrage, etc
    "exchange": "muesliswap",           # Exchange to run the strategy on
    "n_orders": 1,                      # Number of orders to place on each side of the order book
    "delta": 0.05,                      # Distance between orders as a fraction of the mid price
    "order_refresh_threshold": 0.3,    # Percentage change in price to trigger order refresh
    "loop_interval": 5,                 # Time in seconds between each loop
    "tokens": {                         # Tokens to trade
        "MILKv2": {                                                               
            "hexname": "4d494c4b7632",
            "policy_id": "afbe91c0b44b3040e360057bf8354ead8c49c4979ae6ab7c4fbdc9eb",
            "amount": 1000000,   # Amount tokens per trade including decimals
            "decimals": 6 # Number of decimals in the token
        }
    }
}